# Generated by Django 2.2.28 on 2022-07-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shirts', models.IntegerField()),
                ('shorts', models.IntegerField()),
                ('trousers', models.IntegerField()),
                ('total_units', models.CharField(blank=True, max_length=2000)),
                ('shirts_amount', models.CharField(blank=True, max_length=2000)),
                ('shorts_amount', models.CharField(blank=True, max_length=2000)),
                ('trousers_amount', models.CharField(blank=True, max_length=2000)),
                ('total', models.CharField(blank=True, max_length=2000)),
                ('verified', models.BooleanField(null=True)),
                ('picked_up', models.BooleanField(null=True)),
                ('doing_laundry', models.BooleanField(null=True)),
                ('delivery_underway', models.BooleanField(null=True)),
                ('delivered', models.BooleanField(null=True)),
                ('address', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
