# Generated by Django 2.2.28 on 2022-07-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='picked_up',
        ),
    ]
